-- Ejecutar una sola vez en el SQL Editor de CADA proyecto Supabase nuevo.
do $$ begin
  create type public.bot_state as enum (
    'GREETING', 'PRODUCT_SELECTION', 'FORMAT_SELECTION', 'QUANTITY_SELECTION',
    'PAYMENT_PENDING', 'PICKUP_INSTRUCTIONS', 'HUMAN_HANDOFF'
  );
exception when duplicate_object then null;
end $$;

create table if not exists public.customers (
  id uuid default gen_random_uuid() primary key,
  phone_number varchar(25) unique not null,
  name varchar(100),
  created_at timestamptz default now()
);

create table if not exists public.conversation_states (
  phone_number varchar(25) primary key references public.customers(phone_number),
  current_state public.bot_state default 'GREETING',
  is_paused boolean default false,
  handoff_reason varchar(255),
  retry_count integer default 0,
  last_interaction timestamptz default now(),
  chatwoot_conversation_id integer,
  follow_up_token varchar
);

create table if not exists public.message_logs (
  id bigint generated by default as identity primary key,
  phone_number varchar(25) not null references public.customers(phone_number),
  role varchar(20) not null check (role in ('user', 'model')),
  content text not null default '',
  created_at timestamptz default now()
);

create table if not exists public.orders (
  id uuid default gen_random_uuid() primary key,
  customer_id uuid references public.customers(id),
  product varchar(100), format varchar(100), quantity integer,
  total_price numeric(12,2), payment_receipt_url text,
  status varchar(50) default 'PENDING_PAYMENT',
  created_at timestamptz default now()
);

create table if not exists public.processed_webhook_events (
  source varchar(50) not null, event_id varchar(255) not null,
  phone_number varchar(50), status varchar(50) not null default 'received',
  received_at timestamptz default now(), processed_at timestamptz, error text,
  primary key (source, event_id)
);

create index if not exists idx_message_logs_phone_created_at on public.message_logs(phone_number, created_at desc, id desc);
create index if not exists idx_states_paused on public.conversation_states(is_paused);
create index if not exists idx_orders_customer on public.orders(customer_id);
create index if not exists idx_conversation_states_chatwoot_conversation_id on public.conversation_states(chatwoot_conversation_id) where chatwoot_conversation_id is not null;
create unique index if not exists uq_conversation_states_active_chatwoot_conversation_id on public.conversation_states(chatwoot_conversation_id) where chatwoot_conversation_id is not null;
