-- Run once in a NEW Supabase project's SQL Editor.
-- This schema contains only the tables used by the current bot runtime.
DO $$ BEGIN
  CREATE TYPE public.bot_state AS ENUM (
    'GREETING', 'PRODUCT_SELECTION', 'FORMAT_SELECTION', 'QUANTITY_SELECTION',
    'PAYMENT_PENDING', 'PICKUP_INSTRUCTIONS', 'HUMAN_HANDOFF'
  );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS public.customers (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  phone_number varchar(25) UNIQUE NOT NULL,
  name varchar(100),
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.conversation_states (
  phone_number varchar(25) PRIMARY KEY REFERENCES public.customers(phone_number),
  current_state public.bot_state DEFAULT 'GREETING',
  is_paused boolean DEFAULT false,
  handoff_reason varchar(255),
  retry_count integer DEFAULT 0,
  last_interaction timestamptz DEFAULT now(),
  chatwoot_conversation_id integer,
  follow_up_token varchar
);

CREATE TABLE IF NOT EXISTS public.message_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phone_number varchar(25) NOT NULL REFERENCES public.customers(phone_number),
  -- Runtime also records operational events such as handoffs, catalog sends,
  -- and Chatwoot resolutions. Keep this constraint aligned with bot.py/main.py.
  role varchar(20) NOT NULL CHECK (role IN ('user', 'model', 'system', 'asesor')),
  content text NOT NULL DEFAULT '',
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.processed_webhook_events (
  source varchar NOT NULL,
  event_id varchar NOT NULL,
  phone_number varchar,
  status varchar NOT NULL DEFAULT 'received',
  received_at timestamptz DEFAULT now(),
  processed_at timestamptz,
  error text,
  PRIMARY KEY (source, event_id)
);

CREATE INDEX IF NOT EXISTS idx_message_logs_phone_created_at
  ON public.message_logs(phone_number, created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_conversation_states_chatwoot_conversation_id
  ON public.conversation_states(chatwoot_conversation_id)
  WHERE chatwoot_conversation_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_conversation_states_active_chatwoot_conversation_id
  ON public.conversation_states(chatwoot_conversation_id)
  WHERE chatwoot_conversation_id IS NOT NULL;

INSERT INTO storage.buckets (id, name, public)
VALUES ('catalogos', 'catalogos', true)
ON CONFLICT (id) DO UPDATE SET public = true;
