-- Run once in a NEW Supabase project's SQL Editor (Velvet, Memo's, or another
-- isolated brand). This is the complete current schema: it already includes the
-- queue/idempotency, Chatwoot, follow-up, conversation-memory, catalog Storage,
-- and secured dashboard-admin additions that were applied incrementally to the
-- older Tanaka project. Do not run upgrade_existing_tanaka.sql afterward.
DO $$ BEGIN
  CREATE TYPE public.bot_state AS ENUM (
    'GREETING', 'PRODUCT_SELECTION', 'FORMAT_SELECTION', 'QUANTITY_SELECTION',
    'PAYMENT_PENDING', 'PICKUP_INSTRUCTIONS', 'HUMAN_HANDOFF'
  );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS public.customers (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  phone_number varchar(25) UNIQUE NOT NULL,
  name varchar(100),
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.conversation_states (
  phone_number varchar(25) PRIMARY KEY REFERENCES public.customers(phone_number),
  current_state public.bot_state DEFAULT 'GREETING',
  is_paused boolean DEFAULT false,
  handoff_reason varchar(255),
  retry_count integer DEFAULT 0,
  last_interaction timestamptz DEFAULT now(),
  chatwoot_conversation_id integer,
  follow_up_token varchar,
  customer_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  order_summary text
);

-- Keep this bootstrap safe if it is accidentally rerun after an interrupted or
-- older bootstrap. These are the same feature columns added to legacy Tanaka by
-- upgrade_existing_tanaka.sql and the conversation-memory migration.
ALTER TABLE public.conversation_states
  ADD COLUMN IF NOT EXISTS chatwoot_conversation_id integer,
  ADD COLUMN IF NOT EXISTS follow_up_token varchar,
  ADD COLUMN IF NOT EXISTS customer_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS order_summary text;

CREATE TABLE IF NOT EXISTS public.message_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phone_number varchar(25) NOT NULL REFERENCES public.customers(phone_number),
  role varchar(20) NOT NULL CHECK (role IN ('user', 'model', 'system', 'asesor')),
  content text NOT NULL DEFAULT '',
  created_at timestamptz DEFAULT now()
);

-- Canonical equivalent of enable_runtime_message_roles.sql: runtime delivery
-- markers and Chatwoot history use `system` and `asesor`. Keeping this in the main
-- initializer means every future brand is correct without a follow-up repair.
-- Replace the older two-role constraint if an interrupted/early bootstrap created it.
ALTER TABLE public.message_logs DROP CONSTRAINT IF EXISTS message_logs_role_check;
ALTER TABLE public.message_logs
  ADD CONSTRAINT message_logs_role_check
  CHECK (role IN ('user', 'model', 'system', 'asesor'));

CREATE TABLE IF NOT EXISTS public.processed_webhook_events (
  source varchar NOT NULL,
  event_id varchar NOT NULL,
  phone_number varchar,
  status varchar NOT NULL DEFAULT 'received',
  received_at timestamptz DEFAULT now(),
  processed_at timestamptz,
  error text,
  PRIMARY KEY (source, event_id)
);

-- Optional dashboard allow-list. It is created for feature parity even when the
-- current deployment uses only the password proxy. Only service-role code may
-- read/write it; browser roles receive no policy or table grants.
CREATE TABLE IF NOT EXISTS public.dashboard_admins (
  user_id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.dashboard_admins ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.dashboard_admins FROM anon, authenticated;

CREATE INDEX IF NOT EXISTS idx_message_logs_phone_created_at
  ON public.message_logs(phone_number, created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_conversation_states_chatwoot_conversation_id
  ON public.conversation_states(chatwoot_conversation_id)
  WHERE chatwoot_conversation_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_conversation_states_active_chatwoot_conversation_id
  ON public.conversation_states(chatwoot_conversation_id)
  WHERE chatwoot_conversation_id IS NOT NULL;

INSERT INTO storage.buckets (id, name, public)
VALUES ('catalogos', 'catalogos', true)
ON CONFLICT (id) DO UPDATE SET public = true;

CREATE TABLE IF NOT EXISTS public.catalog_assets (
  business_id text NOT NULL,
  catalog_id text NOT NULL CHECK (catalog_id ~ '^catalogo_[a-z0-9_]{1,52}$'),
  public_name text NOT NULL CHECK (length(trim(public_name)) BETWEEN 1 AND 120),
  description text NOT NULL CHECK (length(trim(description)) BETWEEN 1 AND 500),
  media_type text NOT NULL DEFAULT 'document' CHECK (media_type IN ('document', 'image')),
  filename text,
  content_type text CHECK (content_type IN ('application/pdf', 'image/jpeg', 'image/png', 'image/webp')),
  size_bytes bigint CHECK (size_bytes IS NULL OR size_bytes >= 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (business_id, catalog_id)
);
ALTER TABLE public.catalog_assets ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.catalog_assets FROM anon, authenticated;

-- Read-only verification: every value must be true before connecting Railway.
SELECT
  to_regclass('public.customers') IS NOT NULL AS has_customers,
  to_regclass('public.conversation_states') IS NOT NULL AS has_conversation_states,
  to_regclass('public.message_logs') IS NOT NULL AS has_message_logs,
  to_regclass('public.processed_webhook_events') IS NOT NULL AS has_webhook_events,
  to_regclass('public.dashboard_admins') IS NOT NULL AS has_dashboard_admins,
  to_regclass('public.catalog_assets') IS NOT NULL AS has_catalog_assets,
  EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'conversation_states'
      AND column_name = 'follow_up_token'
  ) AS has_follow_up_token,
  EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'conversation_states'
      AND column_name = 'customer_data'
  ) AS has_customer_data,
  EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'conversation_states'
      AND column_name = 'order_summary'
  ) AS has_order_summary,
  to_regclass('public.uq_conversation_states_active_chatwoot_conversation_id') IS NOT NULL
    AS has_unique_chatwoot_index,
  EXISTS (
    SELECT 1 FROM storage.buckets WHERE id = 'catalogos' AND public
  ) AS has_public_catalog_bucket;
