#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WIDGET="$ROOT/kommo_widget"
OUTPUT="$ROOT/dist/kommo-salesbot-widget.zip"
STAGING="$(mktemp -d)"
trap 'rm -rf "$STAGING"' EXIT

: "${KOMMO_WIDGET_CODE:?Set KOMMO_WIDGET_CODE to a unique lowercase widget code}"
: "${KOMMO_WIDGET_SECRET_KEY:?Set KOMMO_WIDGET_SECRET_KEY to the Secret key generated by Kommo}"

if [[ ! "$KOMMO_WIDGET_CODE" =~ ^[a-z][a-z0-9_]{2,63}$ ]]; then
  echo "KOMMO_WIDGET_CODE must match ^[a-z][a-z0-9_]{2,63}$" >&2
  exit 1
fi

cp -R "$WIDGET/i18n" "$WIDGET/images" "$WIDGET/script.js" "$STAGING/"
python3 - "$WIDGET/manifest.json" "$STAGING/manifest.json" <<'PY'
import json
import os
import sys

with open(sys.argv[1], encoding="utf-8") as source:
    manifest = json.load(source)
manifest["widget"]["code"] = os.environ["KOMMO_WIDGET_CODE"]
manifest["widget"]["secret_key"] = os.environ["KOMMO_WIDGET_SECRET_KEY"]
with open(sys.argv[2], "w", encoding="utf-8", newline="\n") as target:
    json.dump(manifest, target, ensure_ascii=False, indent=2)
    target.write("\n")
PY

python3 "$WIDGET/generate_images.py"
rm -rf "$STAGING/images"
cp -R "$WIDGET/images" "$STAGING/images"
python3 -m json.tool "$STAGING/manifest.json" >/dev/null
python3 -m json.tool "$WIDGET/i18n/es.json" >/dev/null

mkdir -p "$ROOT/dist"
rm -f "$OUTPUT"
(
  cd "$STAGING"
  zip -q -r "$OUTPUT" manifest.json script.js i18n/es.json images
)

python3 - "$OUTPUT" <<'PY'
import sys
import zipfile

with zipfile.ZipFile(sys.argv[1]) as archive:
    names = archive.namelist()
    assert "manifest.json" in names, "manifest.json must be at the ZIP root"
    assert "kommo_widget/manifest.json" not in names, "do not wrap files in another directory"
    assert all(not name.startswith("/") for name in names)
print(f"Built {sys.argv[1]} ({len(names)} entries)")
PY
